name: 'dbt_test'
version: '1.0.0'
config-version: 2

profile: 'dbt_test'


source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_modules"

vars:
    start_date: '2020-01-01'
    finish_date: '2020-03-31'
    

models:
  dbt_test:
    +materialized: view
